### ISSUE TITLE
How do I use webpack source maps in vscode debugger? 

### ISSUE THREAD

**Issue by tohagan** [mpotthoff/vscode-android-webview-debug#1]
First up .. a massive Thank You. I badly needed this plugin. 
I'm trying to debug a mobile app built with [quasar-framework](https://quasar-framework.org/). 
Quasar generates webpack compressed JS & CSS with source maps via this command line:

     quasar build -m pwa -debug

So I'm wondering how do I get the VSCode debugger to use these source maps?

Tony's "Thank You" Tip: 
I used to use a QR code open the web app on the mobile device.
I now just scan a NFC chip ... much faster and simpler.

**Comment by tohagan** [comment]
Solved it ... Wrote you a 5 star review!

**Comment by mpotthoff** [comment]
I'm glad you like it and thanks for the review!
Feel free to open another issue if anymore questions come up. :)
