### ISSUE TITLE
Add to OpenVSX

### ISSUE THREAD

**Issue by bennihtm** [mpotthoff/vscode-android-webview-debug#5]
Is it possible to add the Extension to the OpenVSX Store?

The OpenVSX store is an alternative to the proprietary and vendor-dependend store backend used by Microsoft.
VSCodium - an fully open source distribution of Visual Studio Code uses OpenVSX as a replacement to the Microsoft Store.

The guide on how to add extensions can be found here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by mpotthoff** [comment]
Just a little update: I opened an issue last week to claim my namespace and now I'm waiting for it to get processed.

**Comment by mpotthoff** [comment]
I have taken owner ownership of the extension on OpenVSX and will continue to publish there in the future.
