### ISSUE TITLE
WebView Search is finished before WebView is available

### ISSUE THREAD

**Issue by timvahlbrock** [mpotthoff/vscode-android-webview-debug#7]
Depending on different timing aspects, the extension reports, that no device is hosting a webview to connect to, which is correct, but caused by the application not having completely started yet. Switching between "Launch" and "Attach" mode is tedious. Having the ability to increase the timeout for finding a webview would be great.

**Comment by timvahlbrock** [comment]
As the current approach is not based on wait time, but rather just scans the devices immediately once after deployment, an alternative approach would be allowing to set an amount of retries with a fixed time in between.

**Comment by mpotthoff** [comment]
Fixed with v1.2.1 using the new launch.json option `connectTimeout`.
